[package]
name = "ffi-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
autocxx = "0.26"

[build-dependencies]
autocxx-build = "0.26"
miette = { version = "5", features = ["fancy"] } # optional but gives nicer error messages!